# @package _global_
module:
  _target_: emg2qwerty.lightning.RNNCTCModule
  in_features: 528      # freq * channels = (n_fft // 2 + 1) * 16
  mlp_features: [384]   # Each hand produces 384 features
  rnn_hidden_size: 256
  rnn_num_layers: 2
  dropout: 0.2
  rnn_type: "LSTM"      # Using LSTM instead of GRU
  optimizer: adamw
  lr_scheduler: linear_warmup_cosine_annealing
  decoder: ctc_greedy

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000        # 4 sec windows for 2kHz EMG.
  padding: [1800, 200]       # 900ms past context, 100ms future context.
