# @package _global_
module:
  _target_: emg2qwerty.lightning.ResidualRNNCTCModule
  in_features: 528         # (n_fft // 2 + 1) * 16
  mlp_features: [384]      # Each hand produces 384 features
  rnn_hidden_size: 256
  rnn_num_layers: 2
  dropout: 0.2
  # mlp_features: [512]      # Each hand produces 384 features
  # rnn_hidden_size: 512
  # rnn_num_layers: 4
  # dropout: 0.3
  rnn_type: "GRU"   # GRU, LSTM
  optimizer: adamw
  lr_scheduler: linear_warmup_cosine_annealing
  decoder: ctc_greedy

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000      # 4 sec windows for 2kHz EMG
  padding: [1800, 200]     # 900ms past context, 100ms future context

trainer:
  gradient_clip_val: 1.0
  accumulate_grad_batches: 2
